---
- name: Disable DNSStubListener
  community.general.ini_file:
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: DNSStubListener
    value: "no"
    mode: 0644
  notify: restart systemd-resolved
# - name: Symlink /etc/resolv.conf to /run/systemd/resolve/resolv.conf
#   ansible.builtin.file:
#     src: /run/systemd/resolve/resolv.conf
#     dest: /etc/resolv.conf
#     state: link
#     mode: 06400
