---
- name: Install python dependencies
  ansible.builtin.pip:
    name: github3.py
    state: present

- name: Lookup latest release
  community.general.github_release:
    action: latest_release
    user: AdguardTeam
    repo: Adguardhome
    token: "{% if adguardhome_use_github_token %}{{ lookup('env', 'GITHUB_TOKEN') }}{% endif %}"
  register: adguardhome_latest_release

- name: Set desired version to version of latest release
  ansible.builtin.set_fact:
    adguardhome_version: >-
      {{ adguardhome_latest_release.tag | regex_replace('^v', '') }}
  when: adguardhome_latest_release.tag is defined
