---
- name: Install systemd service
  ansible.builtin.template:
    src: adguardhome.service.j2
    dest: "/etc/systemd/system/{{ adguardhome_service_name }}.service"
    mode: "0664"
  register: adguardhome_systemd_unit
  notify:
    - reload systemd daemon
    - restart adguardhome

- name: Apply configuration settings
  register: settings
  ansible.builtin.template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"
  notify:
    - stop adguardhome
    - apply adguardhome configuration
  tags:
    - molecule-idempotence-notest

- name: Make sure handlers are run
  ansible.builtin.meta: flush_handlers

- name: start and enable adguardhome service
  ansible.builtin.service:
    name: "{{ adguardhome_service_name }}"
    state: started
    enabled: true
