---
- name: Get info about running services
  service_facts:

- name: Install systemd service
  template:
    src: adguardhome.service.j2
    dest: "/etc/systemd/system/{{ adguardhome_service_name }}.service"
    mode: "0664"
  register: adguardhome_systemd_unit
  notify:
    - reload systemd daemon
    - restart adguardhome

- name: Apply configuration settings
  register: settings
  template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"

- name: stop adguardhome service
  service:
    name: "{{ adguardhome_service_name }}"
    state: stopped
  when:
    - settings.changed |bool

- name: apply adguardhome configuration settings
  template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"
  when:
    - settings.changed |bool

- name: start && enable adguardhome service
  service:
    name: "{{ adguardhome_service_name }}"
    state: started
    enabled: true
  when:
    - settings.changed |bool

- name: Get info about running services
  service_facts:

- name: Assert adguardhome service is running
  fail:
    msg: "Seems like AdGuardHome service could not be started. Human intervention required"
  when: ansible_facts.services.get("adguardhome.service", {}).get("state") != "running"
