---
- name: Get info about running services
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: Install systemd service
  ansible.builtin.template:
    src: adguardhome.service.j2
    dest: "/etc/systemd/system/{{ adguardhome_service_name }}.service"
    mode: "0664"
  register: adguardhome_systemd_unit
  notify:
    - reload systemd daemon
    - restart adguardhome

- name: Apply configuration settings
  register: settings
  ansible.builtin.template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"
  notify:
    - stop adguardhome
    - apply adguardhome configuration
    - start and enable adguardhome service

- name: Get info about running services
  ansible.builtin.service_facts:

- name: Assert adguardhome service is running
  ansible.builtin.fail:
    msg: "Seems like AdGuardHome service could not be started. Human intervention required"
  when: ansible_facts.services.get("adguardhome.service", {}).get("state") != "running"
