---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart adguardhome
  ansible.builtin.service:
    name: "{{ adguardhome_service_name }}"
    state: restarted
  when: adguardhome_service_start

- name: stop adguardhome
  ansible.builtin.service:
    name: "{{ adguardhome_service_name }}"
    state: stopped
  when:
    - settings.changed |bool
  tags:
    - molecule-idempotence-notest

- name: apply adguardhome configuration
  ansible.builtin.template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"
  tags:
    - molecule-idempotence-notest

- name: start and enable adguardhome service
  ansible.builtin.service:
    name: "{{ adguardhome_service_name }}"
    state: started
    enabled: true
